### ISSUE TITLE
Unsupported operation: Cannot extract a file path from a c URI

### ISSUE THREAD

**Issue by Curstantine** [fujidaiti/fms#1]
Running build on a windows machine returns the following error:
```
PS PP> flutter pub run fms build material_symbols.yaml
Someting went wrong while processing material_symbols.yaml!
Unsupported operation: Cannot extract a file path from a c URI
```
FWIW, the config file is the exact same as one included in the README file.
Other commands works fine, so I doubt something is wrong with my install.

**Comment by fujidaiti** [comment]
It seems to be the same bug as this [issue](https://github.com/ScerIO/icon_font_generator/issues/19) on icon_font_generator.
I committed to master branch. Could you try using the new version and see if it works fine? Since I don't have windows machine, and the bug is windows related one... You can use the latest version as follows:

```yaml
dev_dependencies:
  fms:
    git:
      url: https://github.com/fujidaiti/fms.git
```

instead of:

```yaml
dev_dependencies:
  fms: ^0.9.0
```

**Comment by Curstantine** [comment]
That certainly fixed the issue, thank you.
